data_postgres:
  image: busybox
  volumes:
    - /var/lib/mysql

postgres:
  image: postgres:10.6
  volumes_from:
    - data_postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USERNAME=postgres
    - POSTGRES_PASSWORD=postgres