version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: circleci/openjdk:8-jdk
    
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }      
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }
      - run: mvn clean install -DskipTests
      - run docker build -f Dockerfile -t $DOCKER_HUB_USER/$DOCKER_HUB_PROJECT:latest .
       - deploy:
          name: Push application Docker image
          commands:
            - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER -p $DOCKERHUB_PASS
            - docker tag DOCKER_HUB_USER/DOCKER_HUB_PROJECT $DOCKER_HUB_USER/DOCKER_HUB_PROJECT:latest
            - docker push $DOCKER_HUB_USER/DOCKER_HUB_PROJECT:latest
