machine:
  pre:
    - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
  services:
    - docker
  java:
    version: oraclejdk8

dependencies:
  pre:
    - docker info
    - mvn dependency:resolve
    - mvn clean package
    - mvn integration-test
    - docker build -f Dockerfile -t $DOCKER_HUB_USER/$DOCKER_HUB_PROJECT:latest .

test:
  post:
    - docker run -d -p 8080:8080 -t lprates/sbdocker;  sleep 10
    - curl --retry 10 --retry-delay 5 -v http://localhost:8080

deployment:
  hub:
    branch: [sb-docker-circleci-example]
    commands:
      - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER -p $DOCKERHUB_PASS
      - docker tag DOCKER_HUB_USER/DOCKER_HUB_PROJECT $DOCKER_HUB_USER/DOCKER_HUB_PROJECT:latest
      - docker push $DOCKER_HUB_USER/DOCKER_HUB_PROJECT:latest
